version: '3.8'

services:
  script:
    build:
      context: .
      dockerfile: Dockerfile.compose-example
    links:
      - redis_ex # устанавливаем ссылку на Redis с именем "redis_ex"

  redis_ex: # меняем имя контейнера на "redis_ex"
    image: redis:alpine
